name: edna
channels:
  - defaults
  - pytorch
  - bioconda
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bottleneck=1.4.2
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - cpuonly=2.0
  - expat=2.7.3
  - fastp=1.0.1
  - filelock=3.20.0
  - gmp=6.3.0
  - gmpy2=2.2.2
  - icu=73.1
  - intel-openmp=2025.0.0
  - isa-l=2.31.1
  - jinja2=3.1.6
  - ld_impl_linux-64=2.44
  - libdeflate=1.25
  - libexpat=2.7.3
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libgomp=15.2.0
  - libhwloc=2.12.1
  - libnsl=2.0.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libxml2=2.13.9
  - libzlib=1.3.1
  - llvm-openmp=14.0.6
  - markupsafe=3.0.2
  - mkl=2025.0.0
  - mkl-service=2.5.2
  - mkl_fft=2.1.1
  - mkl_random=1.3.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.5
  - networkx=3.4.2
  - numexpr=2.14.1
  - numpy=2.2.5
  - numpy-base=2.2.5
  - openssl=3.6.0
  - pandas=2.3.3
  - pip=25.3
  - pthread-stubs=0.3
  - python=3.10.19
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - pytorch=2.5.1
  - pytorch-mutex=1.0
  - pytz=2025.2
  - pyyaml=6.0.3
  - readline=8.3
  - scipy=1.15.3
  - seqkit=2.12.0
  - setuptools=80.9.0
  - six=1.17.0
  - sqlite=3.51.0
  - sympy=1.14.0
  - tbb=2022.3.0
  - tbb-devel=2022.3.0
  - tk=8.6.15
  - typing_extensions=4.15.0
  - tzdata=2025b
  - vsearch=2.30.2
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - yaml=0.2.5
  - zlib=1.3.1
  - pip:
      - hdbscan==0.8.41
      - joblib==1.5.3
      - llvmlite==0.46.0
      - numba==0.63.1
      - pynndescent==0.5.13
      - scikit-learn==1.7.2
      - threadpoolctl==3.6.0
      - tqdm==4.67.1
      - umap-learn==0.5.9.post2
prefix: /home/user1/miniconda3/envs/edna
